[package]
name = "goofycoin"
version = "0.1.0"
authors = ["timolinn <timothyonyiuke@gmail.com>"]
edition = "2018"

[dependencies]
openssl-sys = "0.9"
openssl = "0.10"
nanoid = "0.1.3"
rand = "0.7.3"
hex = "0.4.2"